# Output coloration
if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  alias ls='ls --color=auto'

  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

# Aliases for better directory listings
alias ll='ls -alF'
alias la='ls -A'

alias less='less -r'

# Find in files and output in color to less
function gr() {
  grep -srnH --color=always "$@" . | less -R;
}

# Alias ack-grep to just ack
alias ack='ack-grep'
