# Load the default .bashrc
[[ -s "$HOME/.bashrc" ]] && source "$HOME/.bashrc"

# Load RVM into a shell session as a function
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# Set up byobu launcher
[[ -f /usr/bin/byobu-launch ]] && _byobu_sourced=1 . /usr/bin/byobu-launch
