#  _                 _
# | |__   __ _  ___ | |__
# | '_ \ / _` |/ __|| '_ \
# | |_) | (_| |\__ \| | | |
# |_.__/ \__,_||___/|_| |_|
#

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# This is a stupid way to do this, but apparently when "sourcing", symlinks
# aren't followed, nor does the "~" alias work properly. What's the deal?
HOMEDIR=$(cd && pwd)

source "$HOMEDIR/dotfiles/bash/bash-powerline/bash-powerline.sh"
source "$HOMEDIR/dotfiles/bash/bash_aliases"

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi


# Node Completion - Adapted from auto-generated snippet
shopt -s progcomp
if [ -f ~/.node-completion ]; then
  for f in $(command ls ~/.node-completion); do
    f="$HOME/.node-completion/$f"
    test -f "$f" && . "$f"
  done
fi

# WP-CLI directory
export PATH=~/.wp-cli/bin:$PATH

# Add RVM to PATH for scripting
PATH=$PATH:$HOME/.rvm/bin
